New website design and texts
dapr/website pull request #85
Opened 2023-10-18 13:04 UTC by marcduiker

TODO

- [x] Add latest hero image
- [x] Add images for the 4 value props
- [x] Update value prop texts
- [x] Add latest case studies to testimonials page
- [x] Add Enterprise page with links to Azure Container Apps and Diagrid Conductor.
- [x] Add more end user logos

2023-10-31 18:54 UTC, yaron2 commented on themes/bigspring/layouts/partials/home/adopters.html
> +      <div class="img-container-md vertical-align-center">
For end user logos, please use: NASA, Bosch, IBM, Zeiss, ZScaler, Alibaba Cloud, Rakuten, PwC, Fujitsu, Vonage

2023-11-01 04:16 UTC, yaron2 commented on themes/bigspring/layouts/partials/home/adopters.html
> +      <div class="img-container-md vertical-align-center">
Can also add Lufthansa @marcduiker

2023-11-02 18:21 UTC, yaron2 requested changes

2023-11-02 18:21 UTC, yaron2 commented on content/enterprise/_index.md
> +      link : "https://www.diagrid.io/"
Change to `https://www.diagrid.io/conductor`.

2023-11-02 18:21 UTC, yaron2 commented on content/enterprise/_index.md
> +    summary: "Let Conductor manage Dapr on your Kubernetes cluster so you can focus on writing code. Turn your Kubernetes cluster into a microservices powerhouse. Drastically reduce Dapr operational
Change to: `Fully automated Dapr on any Kubernetes cluster with open-source enterprise support. Drastically reduce Dapr operational overhead while increasing reliability and security. Gain unparalleled visibility into your applications and infrastructure using the telemetry data generated by Dapr. Conductor tracks the health of your entire system and immediately shows you when something is wrong with built-in alerting for every Dapr metric.`

2023-11-02 18:39 UTC, alicejgibbons requested changes
Incorrect links

2023-11-02 18:39 UTC, alicejgibbons commented on data/homepage.yml
> +      link : "https://www.cncf.io/case-studies/at-bay/"
```suggestion
      link : "https://www.cncf.io/case-studies/hdfc-bank/"
```

2023-11-02 18:39 UTC, alicejgibbons commented on data/homepage.yml
> +      link : "https://www.cncf.io/case-studies/at-bay/"
```suggestion
      link : "https://www.cncf.io/case-studies/defacto/"
```

2023-11-02 18:39 UTC, alicejgibbons commented on themes/bigspring/layouts/partials/home/cncf.html
> +    <p>Dapr is a <a href="https://www.cncf.io/sandbox-projects/" class="banner-link">Cloud Native Computing Foundation incubation project</a></p>
```suggestion
    <p>Dapr is a <a href="https://www.cncf.io/projects/#incubating" class="banner-link">Cloud Native Computing Foundation Incubating project</a></p>
```

2023-11-03 13:16 UTC, yaron2 approved these changes

2023-11-03 13:47 UTC, merged